blogging/urls.py
from django.urls import path

from blogging.views import BlogsView, BlogsCreateView, BlogDetailView, BlogUpdateView, BlogDeleteViews

app_name = 'blogs'

urlpatterns = [
    path('', BlogsView.as_view(), name='blogs'),
    path('add_blog/', BlogsCreateView.as_view(), name='add_blog'),
    path('<int:pk>/update_blog/', BlogUpdateView.as_view(), name='blog_update'),
    path('blog_detail/<int:pk>/', BlogDetailView.as_view(), name='blog_detail'),
    path('<int:pk>/blog_delete/', BlogDeleteViews.as_view(), name='blog_delete'),
]

catalog/urls.py
from django.urls import path
from catalog.apps import CatalogConfig
from .views import HomeView, ContactsView, ProductDetailView, ProductCreateView

app_name = CatalogConfig.name

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('contacts/', ContactsView.as_view(), name='contacts'),
    path('product_detail/<int:pk>/', ProductDetailView.as_view(), name='product_detail'),
    path('add_product/', ProductCreateView.as_view(), name='add_product')
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('blogs/', include('blogging.urls', namespace='blogs'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blogging/models.py
from django.db import models


class Blog(models.Model):
    """Создание модели блога, которая будет хранить информацию о блогах"""

    title = models.CharField(max_length=50, verbose_name='Заголовок')
    content = models.TextField(verbose_name='Содержимое')
    preview = models.ImageField(upload_to='images/', verbose_name='Превью')
    created_at = models.DateTimeField(auto_now_add=True)
    sign_of_publication = models.BooleanField(default=False, verbose_name='Опубликовано')
    views_count = models.PositiveIntegerField(default=0, verbose_name='Количество просмотров')

    def __str__(self):
        return f'{self.title} - {self.created_at}'

    class Meta:
        verbose_name = 'Блог'
        verbose_name_plural = 'Блоги'

catalog/models.py
from django.db import models
from django.db.models import CASCADE


class Product(models.Model):
    """Создание модели Product, которая будет хранить информацию о продуктах"""

    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.CharField(max_length=255, verbose_name='Описание')
    image = models.ImageField(upload_to='images/', verbose_name='Изображение')
    category = models.ForeignKey('Category', on_delete=CASCADE)
    purchase_price = models.FloatField(default=0.0, verbose_name='Цена за покупку')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.name}: {self.description}'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ['name']


class Category(models.Model):
    """Создание модели Category, которая будет хранить информацию о категориях"""

    name = models.CharField(max_length=150, verbose_name='Наименование')
    description = models.CharField(max_length=255, verbose_name='Описание')

    def __str__(self):
        return f'{self.name} {self.description}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ['name']

blogging/forms.py
from django import forms
from .models import Blog


class BlogForm(forms.ModelForm):
    """Создаем класс BlogForm, который позволяет автоматически создавать форму на основе модели Blog"""
    class Meta:
        """С помощью класса Meta указываем с какой моделью связана форма и определяем поля"""
        model = Blog
        fields = ['title', 'content', 'preview', 'sign_of_publication']

catalog/forms.py
from django import forms
from .models import Product


class ProductForm(forms.ModelForm):
    """Создаем класс ProductForm, который позволяет автоматически создавать форму на основе модели Product"""
    class Meta:
        """С помощью класса Meta указываем с какой моделью связана форма и определяем поля"""
        model = Product
        fields = ['name', 'description', 'image', 'category', 'purchase_price']


class ContactsForm(forms.Form):
    name = forms.CharField(max_length=100)
    phone = forms.CharField(max_length=15)
    message = forms.CharField(widget=forms.Textarea)

blogging/views.py
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, DetailView, UpdateView, DeleteView
from django.views.generic.edit import CreateView
from django.core.mail import send_mail
from django.conf import settings

from blogging.forms import BlogForm
from blogging.models import Blog


class BlogsView(ListView):
    model = Blog
    template_name = 'blogging/blogs.html'
    context_object_name = 'blogs'

    def get_queryset(self):
        return Blog.objects.all()


class BlogsCreateView(CreateView):
    template_name = 'blogging/add_blog.html'
    form_class = BlogForm
    success_url = reverse_lazy('blogs:blogs')


class BlogUpdateView(UpdateView):
    model = Blog
    fields = ('title', 'content', 'preview', 'sign_of_publication')
    template_name = 'blogging/add_blog.html'
    success_url = reverse_lazy('blogs:blogs')

    def get_success_url(self):
        return reverse('blogs:blog_detail', args=[self.kwargs.get('pk')])


class BlogDetailView(DetailView):
    model = Blog
    template_name = 'blogging/blog_detail.html'
    context_object_name = 'blog'

    def get_object(self, queryset=None):
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()

        if self.object.views_count == 100:
            self.send_notification()

        return self.object

    def send_notification(self):
        subject = 'Блог достиг 100 просмотров!'
        message = f'Ваш блог "{self.object.title}" достиг 100 просмотров.'
        email_from = settings.EMAIL_HOST_USER
        recipient_list = ['kovylek.ul@gmail.com']

        send_mail(subject, message, email_from, recipient_list)


class BlogDeleteViews(DeleteView):
    model = Blog
    success_url = reverse_lazy('blogs:blogs')

catalog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.views.generic import ListView, FormView, DetailView
from django.views.generic.edit import CreateView
from django.urls import reverse_lazy

from catalog.models import Product
from .forms import ProductForm, ContactsForm


class HomeView(ListView):
    model = Product
    template_name = 'home.html'
    context_object_name = 'products'
    paginate_by = 6

    def get_queryset(self):
        return Product.objects.all()


class ContactsView(FormView):
    template_name = 'contacts.html'
    form_class = ContactsForm
    success_url = reverse_lazy('catalog:contacts')

    def form_valid(self, form):
        name = form.cleaned_data['name']
        phone = form.cleaned_data['phone']
        message = form.cleaned_data['message']

        return HttpResponse(f"Спасибо {name}! Ваши данные приняты.")


class ProductDetailView(DetailView):
    model = Product
    template_name = 'product_detail.html'
    context_object_name = 'product'


class ProductCreateView(CreateView):
    template_name = 'add_product.html'
    form_class = ProductForm
    success_url = reverse_lazy('catalog:home')

blogging/templates/blogging/add_blog.html
{% extends 'base.html' %}

{% block title %}Создать блог{% endblock %}

{% block content %}
    {% include 'blogging/menu.html' %}

    <div class="container">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">
                {% if object %}
                Сохранить
                {% else %}
                Создать
                {% endif %}
            </button>
        </form>
    </div>

{% endblock %}

blogging/templates/blogging/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Мой сайт{% endblock %}</title>
    <link rel="stylesheet" type="text/css" href="/static/css/bootstrap.min.css">

</head>
<body>

<div class="container mt-5">
    {% block content %}{% endblock %}
</div>

<div>
    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
            <div class="col-12 col-md">
                SkyStore
                <small class="d-block mb-3 text-muted">&copy; 2023</small>
            </div>
            <div class="col-6 col-md">
                <h5>Категории</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Рассылки</a></li>
                    <li><a class="text-muted" href="#">Телеграм боты</a></li>
                    <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                    <li><a class="text-muted" href="#">Веб-приложения</a></li>
                    <li><a class="text-muted" href="#">Микросервисы</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>Дополнительно</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="#">Мы пишем</a></li>
                </ul>
            </div>
            <div class="col-6 col-md">
                <h5>О нас</h5>
                <ul class="list-unstyled text-small">
                    <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                </ul>
            </div>
        </div>
    </footer>
</div>
<script type="text/javascript" src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

blogging/templates/blogging/blog_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Создать блог{% endblock %}

{% block content %}
    {% include 'blogging/menu.html' %}

    <div class="container">
        <h1 class="mt-5">Удалить блог: {{ blog.title }}?</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <button type="submit" class="btn btn-danger mt-5">Удалить</button>
            <a class="btn btn-primary mt-5" href="{% url 'blogs:blogs' %}">Отменить</a>
        </form>
    </div>

{% endblock %}

blogging/templates/blogging/blog_detail.html
{% extends 'base.html' %}

{% block title%}Блог{% endblock %}

{% block content %}
    {% include 'blogging/menu.html' %}
<div class="container mt-5">
    <h1 class="mb-5">{{ blog.title }}</h1>
    <div class="card">
        <img src="{{ blog.preview.url }}" class="card-img-top" alt="{{ blog.title }}" style="width: 300px; height: auto;">
        <div class="card-body">
            <p class="card-text"><strong>Содержимое:</strong> {{ blog.content }}</p>
            <p class="card-text"><strong>Дата создания:</strong> {{ blog.created_at }}</p>
            <p class="card-text"><strong>Признак публикации:</strong> {{ blog.sign_of_publication }}</p>
            <p class="card-text"><strong>Количество просмотров:</strong> {{ blog.views_count }}</p>
        </div>
    </div>
    <a href="{% url 'blogs:blogs' %}" class="btn btn-primary mt-3">Назад на главную</a>
</div>
{% endblock %}

blogging/templates/blogging/blogs.html
{% extends 'base.html' %}

{% block title %}Главная{% endblock %}

{% block content %}
    {% include 'blogging/menu.html' %}

<div class="container">
    <h1 class="mt-4">Мои блоги</h1>
    <div class="row">
        {% for blog in blogs %}
            {% if blog.sign_of_publication %}
                <div class="col-md-4 mb-4">
                    <div class="card h-100 d-flex flex-column">
                        <img src="{{ blog.preview.url }}" class="card-img-top img-fluid" alt="{{ blog.title }}">
                        <div class="card-body d-flex flex-column flex-grow-1">
                            <h5 class="card-title">{{ blog.title }}</h5>
                            <div class="mt-auto">
                                <a href="{% url 'blogs:blog_detail' blog.id %}" class="btn btn-primary">Читать блог</a>
                                <a href="{% url 'blogs:blog_update' blog.id %}" class="btn btn-primary">Редактировать</a>
                                <a href="{% url 'blogs:blog_delete' blog.id %}" class="btn btn-primary">Удалить</a>
                            </div>
                        </div>
                    </div>
                </div>
            {% endif %}
        {% endfor %}
    </div>

</div>

{% endblock %}

blogging/templates/blogging/menu.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Мой блог</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'blogs:blogs' %}">Главная</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'blogs:add_blog' %}">Добавить блог</a>
    </nav>
</div>

catalog/templates/add_product.html
{% extends 'base.html' %}

{% block title %}Каталог{% endblock %}

{% block content %}
{% include 'menu.html' %}
    <div class="container">
        <h1 class="mt-5">Добавить новый товар</h1>
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="btn btn-primary">Добавить товар</button>
        </form>
        <a href="{% url 'catalog:home' %}" class="btn btn-secondary mt-3">Назад к списку товаров</a>
    </div>
{% endblock %}

catalog/templates/contacts.html
{% extends 'base.html' %}

{% block title %}Контакты{% endblock %}

{% block content %}
{% include 'menu.html' %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>USA</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>Redmond,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя" required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone" placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message" placeholder="Контактный телефон" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

catalog/templates/home.html
{% extends 'base.html' %}

{% block title %}Главная{% endblock %}

{% block content %}
    {% include 'menu.html' %}

    <div class="container">
        <h1 class="mt-4">Список товаров</h1>
        <div class="row">
            {% for product in products %}
            <div class="col-md-4 mb-4">
                <div class="card h-100 d-flex flex-column">
                    <img src="{{ product.image.url }}" class="card-img-top img-fluid" alt="{{ product.name }}">
                    <div class="card-body d-flex flex-column flex-grow-1">
                        <h5 class="card-title">{{ product.name }}</h5>
                        <p class="card-text">{{ product.description|truncatechars:100 }}</p>
                        <div class="mt-auto">
                            <a href="{% url 'catalog:product_detail' product.id %}" class="btn btn-primary">Подробнее</a>
                        </div>
                    </div>
                </div>
            </div>
            {% endfor %}
            <div class="pagination">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page=1">&laquo; Первая</a>
                        <a href="?page={{ page_obj.previous_page_number }}">Предыдущая</a>
                    {% endif %}

                    <span class="current">
                        Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                    </span>

                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">Следующая</a>
                        <a href="?page={{ page_obj.paginator.num_pages }}">Последняя &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </div>
        </div>
    </div>
{% endblock %}

catalog/templates/menu.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Skystore</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:home' %}">Главная</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:add_product' %}">Добавить товар</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'catalog:contacts' %}">Контакты</a>
    </nav>
</div>

catalog/templates/product_detail.html
{% extends 'base.html' %}

{% block title %}Каталог{% endblock %}

{% block content %}
<div class="container mt-5">
    <h1 class="mb-5">{{ product.name }}</h1>
        <div class="card">
            <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.name }}" style="width: 300px; height: auto;">
            <div class="card-body">
                <p class="card-text"><strong>Описание:</strong> {{ product.description }}</p>
                <p class="card-text"><strong>Категория:</strong> {{ product.category.name }}</p>
                <p class="card-text"><strong>Цена за покупку:</strong> {{ product.purchase_price }} руб.</p>
                <p class="card-text"><strong>Дата создания:</strong> {{ product.created_at }}</p>
                <p class="card-text"><strong>Дата обновления:</strong> {{ product.updated_at }}</p>
            </div>
        </div>
    <a href="{% url 'catalog:home' %}" class="btn btn-primary mt-3">Назад на главную</a>
</div>
{% endblock %}